// Generated by gencpp from file projetIntegration/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PROJETINTEGRATION_MESSAGE_ADDTWOINTS_H
#define PROJETINTEGRATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <projetIntegration/AddTwoIntsRequest.h>
#include <projetIntegration/AddTwoIntsResponse.h>


namespace projetIntegration
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace projetIntegration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::projetIntegration::AddTwoInts > {
  static const char* value()
  {
    return "5b7e297ec17d89dc92e7ddef62dccb0a";
  }

  static const char* value(const ::projetIntegration::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::projetIntegration::AddTwoInts > {
  static const char* value()
  {
    return "projetIntegration/AddTwoInts";
  }

  static const char* value(const ::projetIntegration::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::projetIntegration::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::projetIntegration::AddTwoInts >
template<>
struct MD5Sum< ::projetIntegration::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::projetIntegration::AddTwoInts >::value();
  }
  static const char* value(const ::projetIntegration::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::projetIntegration::AddTwoIntsRequest> should match
// service_traits::DataType< ::projetIntegration::AddTwoInts >
template<>
struct DataType< ::projetIntegration::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::projetIntegration::AddTwoInts >::value();
  }
  static const char* value(const ::projetIntegration::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::projetIntegration::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::projetIntegration::AddTwoInts >
template<>
struct MD5Sum< ::projetIntegration::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::projetIntegration::AddTwoInts >::value();
  }
  static const char* value(const ::projetIntegration::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::projetIntegration::AddTwoIntsResponse> should match
// service_traits::DataType< ::projetIntegration::AddTwoInts >
template<>
struct DataType< ::projetIntegration::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::projetIntegration::AddTwoInts >::value();
  }
  static const char* value(const ::projetIntegration::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJETINTEGRATION_MESSAGE_ADDTWOINTS_H
